### ISSUE TITLE
flags.HexColor() panics

### ISSUE THREAD

**Issue by mkevac** [campoy/tools#8]
```
$ go run main.go -h
Usage of /var/folders/5l/qk4j_ghx01945jp0sfx346340000gn/T/go-build749814193/command-line-arguments/_obj/exe/main:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6754a]

goroutine 1 [running]:
panic(0xd7700, 0xc4200100a0)
	/Users/marko/go/src/runtime/panic.go:500 +0x1a1
github.com/campoy/tools/flags.(*hexColor).String(0xc4200103b0, 0xd9280, 0xc4200103b0)
	/Users/marko/goprojects/src/github.com/campoy/tools/flags/color.go:28 +0x3a
flag.isZeroValue(0xc420012240, 0xc42000a2c0, 0x14, 0xf16df)
	/Users/marko/go/src/flag/flag.go:393 +0x12d
flag.(*FlagSet).PrintDefaults.func1(0xc420012240)
	/Users/marko/go/src/flag/flag.go:467 +0x1d5
flag.(*FlagSet).VisitAll(0xc420018120, 0xc420043b88)
	/Users/marko/go/src/flag/flag.go:323 +0x67
flag.(*FlagSet).PrintDefaults(0xc420018120)
	/Users/marko/go/src/flag/flag.go:476 +0x46
flag.PrintDefaults()
	/Users/marko/go/src/flag/flag.go:499 +0x2d
flag.glob..func1()
	/Users/marko/go/src/flag/flag.go:523 +0xce
flag.(*FlagSet).usage(0xc420018120)
	/Users/marko/go/src/flag/flag.go:823 +0x42
flag.(*FlagSet).parseOne(0xc420018120, 0xf16df, 0xa, 0xc420043ec8)
	/Users/marko/go/src/flag/flag.go:870 +0xb4c
flag.(*FlagSet).Parse(0xc420018120, 0xc42000a290, 0x1, 0x1, 0xa, 0xc420010330)
	/Users/marko/go/src/flag/flag.go:915 +0x60
flag.Parse()
	/Users/marko/go/src/flag/flag.go:943 +0x72
main.main()
	/Users/marko/goprojects/src/github.com/mkevac/campoy/main.go:13 +0xa1
exit status 2
```

on a simple program

```
package main

import (
	"flag"
	"fmt"
	"image/color"

	"github.com/campoy/tools/flags"
)

func main() {
	bg := flags.HexColor("bg", color.Black, "background")
	flag.Parse()

	fmt.Printf("%v\n", bg)
}
```

package version 095c53d927c3e146f2a55595663f96c707a1834a

**Comment by campoy** [comment]
sorry I didn't see this before ... could you reproduce it?
it seems like it works on my machine

**Comment by mkevac** [comment]
It works now :-)
